public class Datastruct {

    public static void main(string[] args) {
                 // 0  1  2
        int[] arr= {1, 2, 3};

        int[] arr2= new int[3];

        String[][] multstr= {{"monkey", "gorilla", "lemur"},{"donkey", "horse", "muli"}};

        arr[0]= 4;

        System.out.println(multstr[1][0]);

        for(int i= 0; i < arr.length; i++){ arr= int[3]@10
            System.out.println(arr[i]);
        }

        
    }
}