package main;

import java.util.Random;

public class main{


    public static void(String[] args) {
        double a= Math.PI *2;

        Random r= new Random(10);
        System.out.println(r.nextInt(10));
        System.out.println(r.nextInt(10));
        System.out.println(r.nextInt(10));
        System.out.println(r.nextInt(10));
        System.out.println(r.nextInt(10));
        System.out.println(r.nextInt(10));
        String str= strConcat("String.valueOf(2))", "welt");
    }
}